apiVersion: v1
kind: PersistentVolume
metadata:
  name: kraken-test-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kraken-test-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: kraken-test-pod
spec:
  volumes:
    - name: kraken-test-pv
      persistentVolumeClaim:
        claimName: kraken-test-pvc
  containers:
    - name: kraken-test-container
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
      volumeMounts:
        - mountPath: "/home/krake-dir/"
          name: kraken-test-pv
      securityContext:
        privileged: true
